title: OhTheComet
description: Information Security
author: OTC
avatar: /logo.jpg
email: ohthecomeths@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: ./page:num/

skin: midnight

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
google_analytics: G-JW18T8VT6V

disqus: ohthecomet-github-io

date_format: "%m/%d/%Y %a %I%p"

timezone: Asia/Seoul

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.jpg
social:
  name: OTC
  links:
    - https://github.com/OhTheComet
google_site_verification: QVTOYAcCbFXrV32CqaFbhNYuNzBA75dzHaAdkuNktUs
lang: ko
subscribe: false